apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
data:
  promtail.yaml: |
    client:
     batchsize: 5000000
     batchwait: 1s
     external_labels: {{ toYaml ( .Values.promtailConfig.external_labels ) | nindent 6 }}
     timeout: 10s
    positions:
     filename: /run/promtail/positions.yaml
    server:
     http_listen_port: 3101
    target_config:
     sync_period: 10s
    scrape_configs: {{ toYaml ( .Values.promtailConfig.scrape_configs ) | nindent 6 }}


